version: '3'

services:
  accounts:
    image: 'accounts:latest'
    build:
      context: .
    container_name: accounts
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/accounts
      - SPRING_DATASOURCE_USERNAME=accounts
      - SPRING_DATASOURCE_PASSWORD=accounts
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=accounts
      - POSTGRES_PASSWORD=accounts